// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ2e6OCFYG8bJCrWk8tLBuVidz3WHMExM',
    appId: '1:63292633688:web:f85968d72e036b884c502d',
    messagingSenderId: '63292633688',
    projectId: 'kissansetu1',
    authDomain: 'kissansetu1.firebaseapp.com',
    storageBucket: 'kissansetu1.firebasestorage.app',
    measurementId: 'G-2W3P9F1WZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9VksDlq39c_j-16Q0GCs6gFKi8YeXor8',
    appId: '1:63292633688:android:adafb9559719cc954c502d',
    messagingSenderId: '63292633688',
    projectId: 'kissansetu1',
    storageBucket: 'kissansetu1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBJVm1vE977d2_lE9EVHf_q9lWQ953bCQ',
    appId: '1:63292633688:ios:a2c7fc83427723e04c502d',
    messagingSenderId: '63292633688',
    projectId: 'kissansetu1',
    storageBucket: 'kissansetu1.firebasestorage.app',
    iosBundleId: 'com.example.kisaansetu',
  );
}
